export enum LANGUAGE_MAP {
  Thai = "th",
  Vietnamese = "vi",
  Portugese = "pt",
  SimplifiedChinese = "zh",
  Tagalog = "tl",
  Indo = "id",
  English = "en",
  Russia = "ru",
  Turkish = "tr",
  Spanish = "es",
}
export enum BStorageKey {
  IP_TEST = "IP_TEST",
  LANGUAGE_CHANGE = "LANGUAGE_CHANGE",
  USERNAME = "USERNAME",
  PASS = "PASS",
  MUSIC = "MUSIC",
  SOUND = "SOUND",
  SHOW_WELCOME = "SHOW_WELCOME",
  LANGUAGE_DATA = "LANGUAGE_DATA",
  LANGUAGE_CACHE = "LANGUAGE_CACHE",
}
export enum BNotifyType {
  LANGUAGE_CHANGED = "LANGUAGE_CHANGED", //
  BLOCK_INPUT_SHOW = "BLOCK_INPUT_SHOW", // active block input
  BLOCK_INPUT_HIDE = "BLOCK_INPUT_HIDE", // disable block input
  CHANGE_MONEY = "CHANGE_MONEY",
  INPUT_ACTION = "INPUT_ACTION",
  TAP_EFFECT = "TAP_EFFECT",
  UPDATE_GAME_MODE = "UPDATE_GAME_MODE",
  TREND_CHANGE = "TREND_CHANGE",
  ADD_TREND = "ADD_TREND",
  RUN_AUTO = "RUN_AUTO",
  STOP_AUTO = "STOP_AUTO",
  MUSIC_CHANGE = "MUSIC_CHANGE",
  SOUND_CHANGE = "SOUND_CHANGE",
  CHANGE_GAME_INFO = "CHANGE_GAME_INFO",
  SOUND_CLICK = "SOUND_CLICK",
  SHOW_MESSAGE = "SHOW_MESSAGE",
  HIDE_MESSAGE = "HIDE_MESSAGE",
  SHOW_DISCONNECT = "SHOW_DISCONNECT",
  HIDE_DISCONNECT = "HIDE_DISCONNECT",
  RECONNECT_SERVER = "RECONNECT_SERVER",

  SHOW_WELCOME = "SHOW_WELCOME",
  HIDE_WELCOME = "HIDE_WELCOME",
  UPDATE_BET_AMOUT = "UPDATE_BET_AMOUT",
  UPDATE_AVATA = "UPDATE_AVATA",
  RUN_ANIM_AVATA = "RUN_ANIM_AVATA",
  GAME_PAUSE = "GAME_PAUSE",
  SHOW_HELP = "SHOW_HELP",
  HIDE_HELP = "HIDE_HELP",
  SHOW_HISTORY = "SHOW_HISTORY",
  HISTORY_UPDATE = "HISTORY_UPDATE",
  RESET_GAME = "RESET_GAME",
}
export enum TEXT_TYPE {
  NONE,
  FIRST_UP,
  UP_CASE,
  NORMAL,
}
